# D:\resume Sacnner\.streamlit\secrets.toml
GEMINI_API_KEY = "AIzaSyD995NJQZDPJVvj18U5APPgdTqt-GT-H0w"
DATABASE_URL=postgresql://neondb_owner:npg_blorOJ8f1vyZ@ep-dry-band-adni8kqj-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require